import psycopg2

conn = psycopg2.connect(
    host='srv1353769.hstgr.cloud',
    port=32768,
    user='A39bokKZClHrBqXC',
    password='ex4x8VZVSogaZL0Bpvj7oGNJkFoWbT0K',
    dbname='kanbamlicita',
    connect_timeout=10,
    sslmode='disable'
)
conn.autocommit = True
cur = conn.cursor()

statements = [
    'CREATE SCHEMA IF NOT EXISTS "public"',
    """CREATE TYPE "KanbanColuna" AS ENUM ('captadas_automaticamente','triagem_inicial','em_analise','viavel_comercialmente','proposta_documentacao','enviadas_participando','ganhamos','perdemos','descartadas')""",
    """CREATE TABLE "licitacoes" (
        "id" TEXT NOT NULL,
        "id_externo" VARCHAR(120),
        "fonte_captacao" VARCHAR(50),
        "link_origem" TEXT,
        "orgao" TEXT,
        "numero_licitacao" VARCHAR(120),
        "numero_processo" VARCHAR(120),
        "modalidade" VARCHAR(80),
        "tipo_disputa" VARCHAR(80),
        "criterio_julgamento" VARCHAR(120),
        "objeto_resumido" TEXT,
        "segmento" VARCHAR(80),
        "data_publicacao" DATE,
        "data_sessao" TIMESTAMP(3),
        "uf" CHAR(2),
        "municipio" VARCHAR(120),
        "regiao" VARCHAR(50),
        "valor_global_estimado" DECIMAL(18,2),
        "moeda" CHAR(3) NOT NULL DEFAULT 'BRL',
        "possui_lotes" BOOLEAN NOT NULL DEFAULT false,
        "possui_itens" BOOLEAN NOT NULL DEFAULT false,
        "possui_planilha_orcamentaria" BOOLEAN NOT NULL DEFAULT false,
        "possui_quantitativos" BOOLEAN NOT NULL DEFAULT false,
        "possui_precos_unitarios" BOOLEAN NOT NULL DEFAULT false,
        "envolve_locacao" BOOLEAN NOT NULL DEFAULT false,
        "envolve_fornecimento" BOOLEAN NOT NULL DEFAULT false,
        "envolve_servico" BOOLEAN NOT NULL DEFAULT false,
        "envolve_obra" BOOLEAN NOT NULL DEFAULT false,
        "envolve_instalacao" BOOLEAN NOT NULL DEFAULT false,
        "envolve_montagem" BOOLEAN NOT NULL DEFAULT false,
        "envolve_desmontagem" BOOLEAN NOT NULL DEFAULT false,
        "envolve_transporte" BOOLEAN NOT NULL DEFAULT false,
        "envolve_mobilizacao" BOOLEAN NOT NULL DEFAULT false,
        "envolve_desmobilizacao" BOOLEAN NOT NULL DEFAULT false,
        "envolve_manutencao" BOOLEAN NOT NULL DEFAULT false,
        "resumo_natureza" TEXT,
        "status_pipeline" VARCHAR(40) NOT NULL DEFAULT 'pendente',
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "licitacoes_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "kanban_cards" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "coluna_atual" "KanbanColuna" NOT NULL,
        "ordem_coluna" INTEGER NOT NULL DEFAULT 0,
        "responsavel_id" TEXT,
        "urgente" BOOLEAN NOT NULL DEFAULT false,
        "bloqueado" BOOLEAN NOT NULL DEFAULT false,
        "motivo_bloqueio" TEXT,
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "kanban_cards_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "kanban_movimentacoes" (
        "id" TEXT NOT NULL,
        "card_id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "coluna_origem" "KanbanColuna",
        "coluna_destino" "KanbanColuna" NOT NULL,
        "movido_por" TEXT,
        "motivo" TEXT,
        "automatico" BOOLEAN NOT NULL DEFAULT false,
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "kanban_movimentacoes_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "licitacao_score" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "score_final" DECIMAL(5,2) NOT NULL DEFAULT 0,
        "faixa_classificacao" VARCHAR(5) NOT NULL DEFAULT 'D',
        "score_aderencia_direta" DECIMAL(5,2) NOT NULL DEFAULT 0,
        "score_aderencia_aplicacao" DECIMAL(5,2) NOT NULL DEFAULT 0,
        "score_contexto_oculto" DECIMAL(5,2) NOT NULL DEFAULT 0,
        "score_modelo_comercial" DECIMAL(5,2) NOT NULL DEFAULT 0,
        "score_potencial_economico" DECIMAL(5,2) NOT NULL DEFAULT 0,
        "score_qualidade_evidencia" DECIMAL(5,2) NOT NULL DEFAULT 0,
        "score_justificativa_resumida" TEXT,
        "valor_capturavel_obrigatorio_preenchido" BOOLEAN NOT NULL DEFAULT true,
        "valor_capturavel_foi_possivel_estimar" BOOLEAN NOT NULL DEFAULT false,
        "valor_capturavel_estimado" DECIMAL(18,2),
        "valor_capturavel_faixa_min" DECIMAL(18,2),
        "valor_capturavel_faixa_max" DECIMAL(18,2),
        "valor_capturavel_moeda" CHAR(3) NOT NULL DEFAULT 'BRL',
        "valor_capturavel_nivel_confianca" VARCHAR(20) NOT NULL DEFAULT 'baixo',
        "valor_capturavel_metodo_estimativa" VARCHAR(50) NOT NULL DEFAULT 'nao_estimado',
        "valor_capturavel_justificativa" TEXT NOT NULL DEFAULT '',
        "valor_capturavel_base_documental" JSONB NOT NULL DEFAULT '[]',
        "valor_capturavel_observacao" TEXT,
        "falso_negativo_obrigatorio_preenchido" BOOLEAN NOT NULL DEFAULT true,
        "falso_negativo_existe_risco" BOOLEAN NOT NULL DEFAULT false,
        "falso_negativo_nivel_risco" VARCHAR(20) NOT NULL DEFAULT 'baixo',
        "falso_negativo_motivos" JSONB NOT NULL DEFAULT '[]',
        "falso_negativo_trechos_criticos" JSONB NOT NULL DEFAULT '[]',
        "falso_negativo_resumo" TEXT NOT NULL DEFAULT '',
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "licitacao_score_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "licitacao_documentos" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "possui_edital" BOOLEAN NOT NULL DEFAULT false,
        "possui_termo_referencia" BOOLEAN NOT NULL DEFAULT false,
        "possui_projeto_basico" BOOLEAN NOT NULL DEFAULT false,
        "possui_memorial_descritivo" BOOLEAN NOT NULL DEFAULT false,
        "possui_anexos_tecnicos" BOOLEAN NOT NULL DEFAULT false,
        "possui_planilha_orcamentaria" BOOLEAN NOT NULL DEFAULT false,
        "possui_cronograma" BOOLEAN NOT NULL DEFAULT false,
        "possui_minuta_contratual" BOOLEAN NOT NULL DEFAULT false,
        "lacunas_documentais" TEXT,
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "licitacao_documentos_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "licitacao_sinais" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "categoria" VARCHAR(50) NOT NULL,
        "subcategoria" VARCHAR(50),
        "sinal" TEXT NOT NULL,
        "nivel" VARCHAR(30),
        "trecho" TEXT,
        "fonte_documento" VARCHAR(80),
        "relevancia" VARCHAR(20),
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "licitacao_sinais_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "licitacao_itens" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "tipo" VARCHAR(20),
        "identificador" VARCHAR(80),
        "descricao" TEXT,
        "quantitativo" DECIMAL(18,4),
        "unidade" VARCHAR(30),
        "aderencia" VARCHAR(20) NOT NULL DEFAULT 'nenhuma',
        "tipo_aderencia" VARCHAR(30) NOT NULL DEFAULT 'nenhuma',
        "prioridade" VARCHAR(20) NOT NULL DEFAULT 'baixa',
        "valor_estimado_item" DECIMAL(18,2),
        "motivo" TEXT,
        "observacoes" TEXT,
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "licitacao_itens_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "licitacao_analise" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "aderencia_direta_existe" BOOLEAN NOT NULL DEFAULT false,
        "aderencia_direta_nivel" VARCHAR(20) NOT NULL DEFAULT 'nenhuma',
        "aderencia_aplicacao_existe" BOOLEAN NOT NULL DEFAULT false,
        "aderencia_aplicacao_nivel" VARCHAR(20) NOT NULL DEFAULT 'nenhuma',
        "contexto_oculto_existe" BOOLEAN NOT NULL DEFAULT false,
        "contexto_oculto_nivel" VARCHAR(20) NOT NULL DEFAULT 'nenhuma',
        "modelo_comercial_existe" BOOLEAN NOT NULL DEFAULT false,
        "modelo_comercial_nivel" VARCHAR(20) NOT NULL DEFAULT 'nenhum',
        "oportunidade_oculta_existe" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_oculta_forca" VARCHAR(20) NOT NULL DEFAULT 'nenhuma',
        "oportunidade_oculta_resumo" TEXT,
        "oportunidade_no_objeto" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_no_tr" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_nos_lotes" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_nos_itens" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_na_planilha" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_no_memorial" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_em_anexo_tecnico" BOOLEAN NOT NULL DEFAULT false,
        "portfolio_aplicavel" JSONB NOT NULL DEFAULT '[]',
        "solucoes_multiteiner_aplicaveis" JSONB NOT NULL DEFAULT '[]',
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "licitacao_analise_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "licitacao_parecer" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "classificacao_final" VARCHAR(5) NOT NULL DEFAULT 'D',
        "prioridade_comercial" VARCHAR(20) NOT NULL DEFAULT 'baixa',
        "vale_esforco_comercial" BOOLEAN NOT NULL DEFAULT false,
        "recomendacao_final" VARCHAR(40) NOT NULL DEFAULT 'DESCARTAR',
        "resumo" TEXT,
        "oportunidade_direta" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_indireta" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_oculta_item_lote_anexo" BOOLEAN NOT NULL DEFAULT false,
        "oportunidade_inexistente" BOOLEAN NOT NULL DEFAULT true,
        "onde_esta_oportunidade" JSONB NOT NULL DEFAULT '[]',
        "solucoes_que_multiteiner_poderia_ofertar" JSONB NOT NULL DEFAULT '[]',
        "proximo_passo_recomendado" JSONB NOT NULL DEFAULT '[]',
        "riscos_limitacoes" JSONB NOT NULL DEFAULT '[]',
        "evidencias_principais" JSONB NOT NULL DEFAULT '[]',
        "risco_falso_positivo" VARCHAR(20) NOT NULL DEFAULT 'baixo',
        "risco_falso_negativo_so_titulo" VARCHAR(20) NOT NULL DEFAULT 'baixo',
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "licitacao_parecer_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "licitacao_analises_ia" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "tipo_analise" VARCHAR(50) NOT NULL,
        "status" VARCHAR(30) NOT NULL DEFAULT 'pendente',
        "modelo_utilizado" VARCHAR(80),
        "prompt_versao" VARCHAR(40),
        "resultado_json" JSONB NOT NULL DEFAULT '{}',
        "resumo_texto" TEXT,
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "licitacao_analises_ia_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "captacao_fontes" (
        "id" TEXT NOT NULL,
        "nome" VARCHAR(100) NOT NULL,
        "tipo" VARCHAR(50) NOT NULL,
        "endpoint_base" TEXT,
        "ativo" BOOLEAN NOT NULL DEFAULT true,
        "autenticacao_tipo" VARCHAR(50),
        "configuracao" JSONB NOT NULL DEFAULT '{}',
        "ultima_sincronizacao" TIMESTAMP(3),
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "atualizado_em" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "captacao_fontes_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "captacao_execucoes" (
        "id" TEXT NOT NULL,
        "fonte_id" TEXT NOT NULL,
        "iniciado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "finalizado_em" TIMESTAMP(3),
        "status" VARCHAR(30) NOT NULL DEFAULT 'rodando',
        "total_lidos" INTEGER NOT NULL DEFAULT 0,
        "total_novos" INTEGER NOT NULL DEFAULT 0,
        "total_atualizados" INTEGER NOT NULL DEFAULT 0,
        "total_descartados_duplicidade" INTEGER NOT NULL DEFAULT 0,
        "total_erros" INTEGER NOT NULL DEFAULT 0,
        "log_resumo" TEXT,
        CONSTRAINT "captacao_execucoes_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "captacao_payloads" (
        "id" TEXT NOT NULL,
        "execucao_id" TEXT NOT NULL,
        "fonte_id" TEXT NOT NULL,
        "id_externo_origem" VARCHAR(200),
        "payload_bruto" JSONB NOT NULL,
        "hash_payload" VARCHAR(128),
        "capturado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "status_processamento" VARCHAR(30) NOT NULL DEFAULT 'pendente',
        "erro_processamento" TEXT,
        CONSTRAINT "captacao_payloads_pkey" PRIMARY KEY ("id")
    )""",
    """CREATE TABLE "licitacao_aliases_origem" (
        "id" TEXT NOT NULL,
        "licitacao_id" TEXT NOT NULL,
        "fonte_id" TEXT NOT NULL,
        "id_externo_origem" VARCHAR(200) NOT NULL,
        "hash_deduplicacao" VARCHAR(128),
        "objeto_snapshot" TEXT,
        "criado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "licitacao_aliases_origem_pkey" PRIMARY KEY ("id")
    )""",
    'CREATE UNIQUE INDEX "kanban_cards_licitacao_id_key" ON "kanban_cards"("licitacao_id")',
    'CREATE UNIQUE INDEX "licitacao_score_licitacao_id_key" ON "licitacao_score"("licitacao_id")',
    'CREATE UNIQUE INDEX "licitacao_documentos_licitacao_id_key" ON "licitacao_documentos"("licitacao_id")',
    'CREATE UNIQUE INDEX "licitacao_analise_licitacao_id_key" ON "licitacao_analise"("licitacao_id")',
    'CREATE UNIQUE INDEX "licitacao_parecer_licitacao_id_key" ON "licitacao_parecer"("licitacao_id")',
    'CREATE UNIQUE INDEX "licitacao_aliases_origem_fonte_id_id_externo_origem_key" ON "licitacao_aliases_origem"("fonte_id", "id_externo_origem")',
    'ALTER TABLE "kanban_cards" ADD CONSTRAINT "kanban_cards_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "kanban_movimentacoes" ADD CONSTRAINT "kanban_movimentacoes_card_id_fkey" FOREIGN KEY ("card_id") REFERENCES "kanban_cards"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "kanban_movimentacoes" ADD CONSTRAINT "kanban_movimentacoes_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_score" ADD CONSTRAINT "licitacao_score_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_documentos" ADD CONSTRAINT "licitacao_documentos_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_sinais" ADD CONSTRAINT "licitacao_sinais_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_itens" ADD CONSTRAINT "licitacao_itens_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_analise" ADD CONSTRAINT "licitacao_analise_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_parecer" ADD CONSTRAINT "licitacao_parecer_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_analises_ia" ADD CONSTRAINT "licitacao_analises_ia_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "captacao_execucoes" ADD CONSTRAINT "captacao_execucoes_fonte_id_fkey" FOREIGN KEY ("fonte_id") REFERENCES "captacao_fontes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "captacao_payloads" ADD CONSTRAINT "captacao_payloads_execucao_id_fkey" FOREIGN KEY ("execucao_id") REFERENCES "captacao_execucoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "captacao_payloads" ADD CONSTRAINT "captacao_payloads_fonte_id_fkey" FOREIGN KEY ("fonte_id") REFERENCES "captacao_fontes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_aliases_origem" ADD CONSTRAINT "licitacao_aliases_origem_licitacao_id_fkey" FOREIGN KEY ("licitacao_id") REFERENCES "licitacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
    'ALTER TABLE "licitacao_aliases_origem" ADD CONSTRAINT "licitacao_aliases_origem_fonte_id_fkey" FOREIGN KEY ("fonte_id") REFERENCES "captacao_fontes"("id") ON DELETE CASCADE ON UPDATE CASCADE',
]

errors = []
for stmt in statements:
    try:
        cur.execute(stmt)
        print(f"OK: {stmt[:60]}...")
    except Exception as e:
        print(f"ERR: {e} | {stmt[:60]}")
        errors.append(str(e))

cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE' ORDER BY table_name")
tables = cur.fetchall()
print(f"\nTables in DB ({len(tables)}): {[t[0] for t in tables]}")
print(f"\nErrors: {len(errors)}")
conn.close()
